services:
  - type: web
    name: spring-ai-rag-app
    runtime: docker
    plan: free
    rootDir: 02-SpringAI-RAG-App
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PORT
        value: 8080
